version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_csharp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: meu_banco_csharp
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password_123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
