<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonTestUtilities\CommonTestUtilities.csproj" />
    <ProjectReference Include="..\..\src\CashFlow.Application\CashFlow.Application.csproj" />
    <ProjectReference Include="..\..\src\CashFlow.Communication\CashFlow.Communication.csproj" />
    <ProjectReference Include="..\..\src\CashFlow.Domain\CashFlow.Domain.csproj" />
    <ProjectReference Include="..\..\src\CashFlow.Exception\CashFlow.Exception.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="xunit" Version="2.8.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.6" />
  </ItemGroup>

</Project>
